spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
